In [67]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\nitesh\anaconda3\ano\lib\site-packages (4.4.3)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\nitesh\anaconda3\ano\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\nitesh\anaconda3\ano\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: trio~=0.17 in c:\users\nitesh\anaconda3\ano\lib\site-packages (from selenium) (0.21.0)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\nitesh\anaconda3\ano\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: async-generator>=1.9 in c:\users\nitesh\anaconda3\ano\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: sortedcontainers in c:\users\nitesh\anaconda3\ano\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\nitesh\anaconda3\ano\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: idna in c:\users\nitesh\anaconda3\ano\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: sniffio in c:\users\nitesh\anaconda3\ano\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\nitesh\anaconda3\ano\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: outcome in c:\users\nitesh\anaconda3\ano\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: pycparser in c:\users\nitesh\anaconda3\ano\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\nitesh\anaconda3\ano\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\nitesh\anaconda3\ano\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\nitesh\anaconda3\ano\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)

In [68]:
!pip install bs4

Requirement already satisfied: bs4 in c:\users\nitesh\anaconda3\ano\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\nitesh\anaconda3\ano\lib\site-packages (from bs4) (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\nitesh\anaconda3\ano\lib\site-packages (from beautifulsoup4->bs4) (2.3.1)

In [2]:
import pandas as pd
from bs4 import BeautifulSoup as bs
from selenium import webdriver

In [3]:
from selenium.webdriver.common.by import By

In [4]:
driver=webdriver.Chrome(executable_path="E:/contact/chromedriver_win32/chromedriver.exe")

C:\Users\nitesh\AppData\Local\Temp\ipykernel_10896\2602234205.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(executable_path="E:/contact/chromedriver_win32/chromedriver.exe")

In [5]:
driver.get("https://www.iplt20.com/stats/2022/")

In [137]:
driver.title

'IPLT20.com | Player Stats | Indian Premier League Website'

In [6]:
l=driver.find_element("link text", "View All")
l.click

In [7]:
data=driver.page_source
data1=bs(data,"html.parser")

In [8]:
msn=data1.find('table',class_="np-mostruns_table statsTable ng-scope")

In [23]:
pos=[]
pl=[]
match=[]
inn=[]
no=[]
runs=[]
hs=[]
avg=[]
bf=[]
sr=[]
hndrd=[]
fif=[]
four=[]
six=[]
rows= msn.find_all('tr')

In [52]:
matchdetail=[]
for row in rows:
    mn=row.find_all(class_='ng-binding')
    for i in range(0,14):
        for da in range(i,len(mn)):
            if da==0:
                pos.append(mn[da].text)
            elif da==1:
                pl.append(mn[da].text)
            elif da==2:
                match.append(mn[da].text)
            elif da==3:
                inn.append(mn[da].text)
            elif da==4:
                no.append(mn[da].text)
            elif da==5:
                runs.append(mn[da].text)
            elif da==6:
                hs.append(mn[da].text)
            elif da==7:
                avg.append(mn[da].text)
            elif da==8:
                bf.append(mn[da].text)
            elif da==9:
                sr.append(mn[da].text)
            elif da==10:
                hndrd.append(mn[da].text)
            elif da==11:
                fif.append(mn[da].text)
            elif da==12:
                four.append(mn[da].text)
            elif da==13:
                six.append(mn[da].text)
            break;

In [53]:
df= {'POS':pos,'PLAYER':pl,'MATCH':match,'INNINGS':inn,'NO':no,'RUNS':runs,'HS':hs,'AVG':avg,'BF':bf,'SR':sr,'HUNDRED':hndrd,'FIFTY':fif,'FOUR':four,'Six':six}

In [54]:
header=['POS','P1','MATCH','INNINGS','NO','RUNS','HS','AVG','BF','SR','HUNDERD','FIFTY','FOUR','SIX']

In [55]:
new = pd.DataFrame.from_dict(df)

In [56]:
new

,POS,PLAYER,MATCH,INNINGS,NO,RUNS,HS,AVG,BF,SR,HUNDRED,FIFTY,FOUR,Six
0,1,Jos Buttler,17,17,2,863,116,57.53,579,149.05,4,4,83,45
1,2,K L Rahul,15,15,3,616,103*,51.33,455,135.38,2,4,45,30
2,3,Quinton De Kock,15,15,1,508,140*,36.29,341,148.97,1,3,47,23
3,4,Hardik Pandya,15,15,4,487,87*,44.27,371,131.26,0,4,49,12
4,5,Shubman Gill,16,16,2,483,96,34.50,365,132.32,0,4,51,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,16,Shreyas Iyer,14,14,1,401,85,30.85,298,134.56,0,3,41,11
136,17,Tilak Varma,14,14,3,397,61,36.09,303,131.02,0,2,29,16
137,18,Aiden Markram,14,12,4,381,68*,47.63,274,139.05,0,3,25,19
138,19,Devdutt Padikkal,17,17,0,376,54,22.12,306,122.87,0,1,40,14
139,20,Ruturaj Gaikwad,14,14,0,368,99,26.29,291,126.46,0,3,33,14

In [59]:
csv_data = new.to_csv("ab.csv")

In [58]:
print(csv_data)

,POS,PLAYER,MATCH,INNINGS,NO,RUNS,HS,AVG,BF,SR,HUNDRED,FIFTY,FOUR,Six
0,1,Jos Buttler,17,17,2,863,116,57.53,579,149.05,4,4,83,45
1,2,K L Rahul,15,15,3,616,103*,51.33,455,135.38,2,4,45,30
2,3,Quinton De Kock,15,15,1,508,140*,36.29,341,148.97,1,3,47,23
3,4,Hardik Pandya,15,15,4,487,87*,44.27,371,131.26,0,4,49,12
4,5,Shubman Gill,16,16,2,483,96,34.50,365,132.32,0,4,51,11
5,6,David Miller,16,16,9,481,94*,68.71,337,142.72,0,2,32,23
6,7,Faf Du Plessis,16,16,1,468,96,31.20,367,127.52,0,3,49,13
7,8,Shikhar Dhawan,14,14,2,460,88*,38.33,375,122.66,0,3,47,12
8,9,Sanju Samson,17,17,1,458,55,28.63,312,146.79,0,2,43,26
9,10,Deepak Hooda,15,14,0,451,59,32.21,330,136.66,0,4,36,18
10,11,Liam Livingstone,14,14,2,437,70,36.42,240,182.08,0,4,29,34
11,12,David Warner,12,12,3,432,92*,48.00,287,150.52,0,5,52,15
12,13,Abhishek Sharma,14,14,0,426,75,30.43,320,133.12,0,2,47,13
13,14,Ishan Kishan,14,14,1,418,81*,32.15,348,120.11,0,3,45,11
14,15,Rahul Tripathi,14,14,3,413,76,37.55,261,158.23,0,3,40,20
15,16,Shreyas Iyer,14,14,1,401,85,30.85,298,134.56,0,3,41,11
16,17,Tilak Varma,14,14,3,397,61,36.09,303,131.02,0,2,29,16
17,18,Aiden Markram,14,12,4,381,68*,47.63,274,139.05,0,3,25,19
18,19,Devdutt Padikkal,17,17,0,376,54,22.12,306,122.87,0,1,40,14
19,20,Ruturaj  Gaikwad,14,14,0,368,99,26.29,291,126.46,0,3,33,14
20,1,Jos Buttler,17,17,2,863,116,57.53,579,149.05,4,4,83,45
21,2,K L Rahul,15,15,3,616,103*,51.33,455,135.38,2,4,45,30
22,3,Quinton De Kock,15,15,1,508,140*,36.29,341,148.97,1,3,47,23
23,4,Hardik Pandya,15,15,4,487,87*,44.27,371,131.26,0,4,49,12
24,5,Shubman Gill,16,16,2,483,96,34.50,365,132.32,0,4,51,11
25,6,David Miller,16,16,9,481,94*,68.71,337,142.72,0,2,32,23
26,7,Faf Du Plessis,16,16,1,468,96,31.20,367,127.52,0,3,49,13
27,8,Shikhar Dhawan,14,14,2,460,88*,38.33,375,122.66,0,3,47,12
28,9,Sanju Samson,17,17,1,458,55,28.63,312,146.79,0,2,43,26
29,10,Deepak Hooda,15,14,0,451,59,32.21,330,136.66,0,4,36,18
30,11,Liam Livingstone,14,14,2,437,70,36.42,240,182.08,0,4,29,34
31,12,David Warner,12,12,3,432,92*,48.00,287,150.52,0,5,52,15
32,13,Abhishek Sharma,14,14,0,426,75,30.43,320,133.12,0,2,47,13
33,14,Ishan Kishan,14,14,1,418,81*,32.15,348,120.11,0,3,45,11
34,15,Rahul Tripathi,14,14,3,413,76,37.55,261,158.23,0,3,40,20
35,16,Shreyas Iyer,14,14,1,401,85,30.85,298,134.56,0,3,41,11
36,17,Tilak Varma,14,14,3,397,61,36.09,303,131.02,0,2,29,16
37,18,Aiden Markram,14,12,4,381,68*,47.63,274,139.05,0,3,25,19
38,19,Devdutt Padikkal,17,17,0,376,54,22.12,306,122.87,0,1,40,14
39,20,Ruturaj  Gaikwad,14,14,0,368,99,26.29,291,126.46,0,3,33,14
40,1,Jos Buttler,17,17,2,863,116,57.53,579,149.05,4,4,83,45
41,2,K L Rahul,15,15,3,616,103*,51.33,455,135.38,2,4,45,30
42,3,Quinton De Kock,15,15,1,508,140*,36.29,341,148.97,1,3,47,23
43,4,Hardik Pandya,15,15,4,487,87*,44.27,371,131.26,0,4,49,12
44,5,Shubman Gill,16,16,2,483,96,34.50,365,132.32,0,4,51,11
45,6,David Miller,16,16,9,481,94*,68.71,337,142.72,0,2,32,23
46,7,Faf Du Plessis,16,16,1,468,96,31.20,367,127.52,0,3,49,13
47,8,Shikhar Dhawan,14,14,2,460,88*,38.33,375,122.66,0,3,47,12
48,9,Sanju Samson,17,17,1,458,55,28.63,312,146.79,0,2,43,26
49,10,Deepak Hooda,15,14,0,451,59,32.21,330,136.66,0,4,36,18
50,11,Liam Livingstone,14,14,2,437,70,36.42,240,182.08,0,4,29,34
51,12,David Warner,12,12,3,432,92*,48.00,287,150.52,0,5,52,15
52,13,Abhishek Sharma,14,14,0,426,75,30.43,320,133.12,0,2,47,13
53,14,Ishan Kishan,14,14,1,418,81*,32.15,348,120.11,0,3,45,11
54,15,Rahul Tripathi,14,14,3,413,76,37.55,261,158.23,0,3,40,20
55,16,Shreyas Iyer,14,14,1,401,85,30.85,298,134.56,0,3,41,11
56,17,Tilak Varma,14,14,3,397,61,36.09,303,131.02,0,2,29,16
57,18,Aiden Markram,14,12,4,381,68*,47.63,274,139.05,0,3,25,19
58,19,Devdutt Padikkal,17,17,0,376,54,22.12,306,122.87,0,1,40,14
59,20,Ruturaj  Gaikwad,14,14,0,368,99,26.29,291,126.46,0,3,33,14
60,1,Jos Buttler,17,17,2,863,116,57.53,579,149.05,4,4,83,45
61,2,K L Rahul,15,15,3,616,103*,51.33,455,135.38,2,4,45,30
62,3,Quinton De Kock,15,15,1,508,140*,36.29,341,148.97,1,3,47,23
63,4,Hardik Pandya,15,15,4,487,87*,44.27,371,131.26,0,4,49,12
64,5,Shubman Gill,16,16,2,483,96,34.50,365,132.32,0,4,51,11
65,6,David Miller,16,16,9,481,94*,68.71,337,142.72,0,2,32,23
66,7,Faf Du Plessis,16,16,1,468,96,31.20,367,127.52,0,3,49,13
67,8,Shikhar Dhawan,14,14,2,460,88*,38.33,375,122.66,0,3,47,12
68,9,Sanju Samson,17,17,1,458,55,28.63,312,146.79,0,2,43,26
69,10,Deepak Hooda,15,14,0,451,59,32.21,330,136.66,0,4,36,18
70,11,Liam Livingstone,14,14,2,437,70,36.42,240,182.08,0,4,29,34
71,12,David Warner,12,12,3,432,92*,48.00,287,150.52,0,5,52,15
72,13,Abhishek Sharma,14,14,0,426,75,30.43,320,133.12,0,2,47,13
73,14,Ishan Kishan,14,14,1,418,81*,32.15,348,120.11,0,3,45,11
74,15,Rahul Tripathi,14,14,3,413,76,37.55,261,158.23,0,3,40,20
75,16,Shreyas Iyer,14,14,1,401,85,30.85,298,134.56,0,3,41,11
76,17,Tilak Varma,14,14,3,397,61,36.09,303,131.02,0,2,29,16
77,18,Aiden Markram,14,12,4,381,68*,47.63,274,139.05,0,3,25,19
78,19,Devdutt Padikkal,17,17,0,376,54,22.12,306,122.87,0,1,40,14
79,20,Ruturaj  Gaikwad,14,14,0,368,99,26.29,291,126.46,0,3,33,14
80,1,Jos Buttler,17,17,2,863,116,57.53,579,149.05,4,4,83,45
81,2,K L Rahul,15,15,3,616,103*,51.33,455,135.38,2,4,45,30
82,3,Quinton De Kock,15,15,1,508,140*,36.29,341,148.97,1,3,47,23
83,4,Hardik Pandya,15,15,4,487,87*,44.27,371,131.26,0,4,49,12
84,5,Shubman Gill,16,16,2,483,96,34.50,365,132.32,0,4,51,11
85,6,David Miller,16,16,9,481,94*,68.71,337,142.72,0,2,32,23
86,7,Faf Du Plessis,16,16,1,468,96,31.20,367,127.52,0,3,49,13
87,8,Shikhar Dhawan,14,14,2,460,88*,38.33,375,122.66,0,3,47,12
88,9,Sanju Samson,17,17,1,458,55,28.63,312,146.79,0,2,43,26
89,10,Deepak Hooda,15,14,0,451,59,32.21,330,136.66,0,4,36,18
90,11,Liam Livingstone,14,14,2,437,70,36.42,240,182.08,0,4,29,34
91,12,David Warner,12,12,3,432,92*,48.00,287,150.52,0,5,52,15
92,13,Abhishek Sharma,14,14,0,426,75,30.43,320,133.12,0,2,47,13
93,14,Ishan Kishan,14,14,1,418,81*,32.15,348,120.11,0,3,45,11
94,15,Rahul Tripathi,14,14,3,413,76,37.55,261,158.23,0,3,40,20
95,16,Shreyas Iyer,14,14,1,401,85,30.85,298,134.56,0,3,41,11
96,17,Tilak Varma,14,14,3,397,61,36.09,303,131.02,0,2,29,16
97,18,Aiden Markram,14,12,4,381,68*,47.63,274,139.05,0,3,25,19
98,19,Devdutt Padikkal,17,17,0,376,54,22.12,306,122.87,0,1,40,14
99,20,Ruturaj  Gaikwad,14,14,0,368,99,26.29,291,126.46,0,3,33,14
100,1,Jos Buttler,17,17,2,863,116,57.53,579,149.05,4,4,83,45
101,2,K L Rahul,15,15,3,616,103*,51.33,455,135.38,2,4,45,30
102,3,Quinton De Kock,15,15,1,508,140*,36.29,341,148.97,1,3,47,23
103,4,Hardik Pandya,15,15,4,487,87*,44.27,371,131.26,0,4,49,12
104,5,Shubman Gill,16,16,2,483,96,34.50,365,132.32,0,4,51,11
105,6,David Miller,16,16,9,481,94*,68.71,337,142.72,0,2,32,23
106,7,Faf Du Plessis,16,16,1,468,96,31.20,367,127.52,0,3,49,13
107,8,Shikhar Dhawan,14,14,2,460,88*,38.33,375,122.66,0,3,47,12
108,9,Sanju Samson,17,17,1,458,55,28.63,312,146.79,0,2,43,26
109,10,Deepak Hooda,15,14,0,451,59,32.21,330,136.66,0,4,36,18
110,11,Liam Livingstone,14,14,2,437,70,36.42,240,182.08,0,4,29,34
111,12,David Warner,12,12,3,432,92*,48.00,287,150.52,0,5,52,15
112,13,Abhishek Sharma,14,14,0,426,75,30.43,320,133.12,0,2,47,13
113,14,Ishan Kishan,14,14,1,418,81*,32.15,348,120.11,0,3,45,11
114,15,Rahul Tripathi,14,14,3,413,76,37.55,261,158.23,0,3,40,20
115,16,Shreyas Iyer,14,14,1,401,85,30.85,298,134.56,0,3,41,11
116,17,Tilak Varma,14,14,3,397,61,36.09,303,131.02,0,2,29,16
117,18,Aiden Markram,14,12,4,381,68*,47.63,274,139.05,0,3,25,19
118,19,Devdutt Padikkal,17,17,0,376,54,22.12,306,122.87,0,1,40,14
119,20,Ruturaj  Gaikwad,14,14,0,368,99,26.29,291,126.46,0,3,33,14
120,1,Jos Buttler,17,17,2,863,116,57.53,579,149.05,4,4,83,45
121,2,K L Rahul,15,15,3,616,103*,51.33,455,135.38,2,4,45,30
122,3,Quinton De Kock,15,15,1,508,140*,36.29,341,148.97,1,3,47,23
123,4,Hardik Pandya,15,15,4,487,87*,44.27,371,131.26,0,4,49,12
124,5,Shubman Gill,16,16,2,483,96,34.50,365,132.32,0,4,51,11
125,6,David Miller,16,16,9,481,94*,68.71,337,142.72,0,2,32,23
126,7,Faf Du Plessis,16,16,1,468,96,31.20,367,127.52,0,3,49,13
127,8,Shikhar Dhawan,14,14,2,460,88*,38.33,375,122.66,0,3,47,12
128,9,Sanju Samson,17,17,1,458,55,28.63,312,146.79,0,2,43,26
129,10,Deepak Hooda,15,14,0,451,59,32.21,330,136.66,0,4,36,18
130,11,Liam Livingstone,14,14,2,437,70,36.42,240,182.08,0,4,29,34
131,12,David Warner,12,12,3,432,92*,48.00,287,150.52,0,5,52,15
132,13,Abhishek Sharma,14,14,0,426,75,30.43,320,133.12,0,2,47,13
133,14,Ishan Kishan,14,14,1,418,81*,32.15,348,120.11,0,3,45,11
134,15,Rahul Tripathi,14,14,3,413,76,37.55,261,158.23,0,3,40,20
135,16,Shreyas Iyer,14,14,1,401,85,30.85,298,134.56,0,3,41,11
136,17,Tilak Varma,14,14,3,397,61,36.09,303,131.02,0,2,29,16
137,18,Aiden Markram,14,12,4,381,68*,47.63,274,139.05,0,3,25,19
138,19,Devdutt Padikkal,17,17,0,376,54,22.12,306,122.87,0,1,40,14
139,20,Ruturaj  Gaikwad,14,14,0,368,99,26.29,291,126.46,0,3,33,14

In [ ]:
with open("ipl2022.csv",'w',newline="",encoding='utf-8')as file:
     writer=csv.writer(file)
     writer.writerow(header)
     writer.writerows(matchdetail)

In [ ]:
with open("export.csv", 'w') as csvFile:
        wr = csv.DictWriter(csvFile, fieldnames=col_name)
        wr.writeheader()
        for ele in header
            wr.writerow(ele)